# This is a basic workflow to help you get started with Actions

name: ejercicio-2 CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ ejercicio-2 ]

jobs:
  setup:
    runs-on: ubuntu-latest
    services:
      portal-resultados:
        image: nginx:latest
        ports:
           - 8080:80
    steps:
      - name: proceso de configuraci贸n
        run: |
          echo 'Inicio proceso de configuraci贸n....' > index.html
      - name: verificar configuraci贸n
        run: ls -la /usr/share/ && cat /etc/nginx/nginx.conf
          
  build:
    needs: setup  
    runs-on: ubuntu-latest
    steps:
      - name: proceso de construcci贸n
        run: |
          echo 'Inicio proceso de Construccion....' > index.html
  test:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: proceso de prueba
        run: |
          echo 'Inicio proceso de prueba....' > index.html
      - name: Acceder al portal resultados
        run: curl http://localhost:8080
    
  
