# This is a basic workflow to help you get started with Actions

name: ejercicio-1 CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ejercicio-1]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: crear 5 archivos
        run: |
          mkdir artefacto
          mkdir archivos && cd archivos
          echo 'Contenido archivo 1' > archivo1.txt
          echo 'Contenido archivo 2' > archivo2.txt
          echo 'Contenido archivo 3' > archivo3.txt 
          echo 'Contenido archivo 4' > archivo4.txt
          echo 'Contenido archivo 5' > archivo5.txt                   
          cd ..

      - name: comprimir archivos
        uses: papeloto/action-zip@v1
        with:
          files: archivos/
          dest: archivos.zip

      - name: Subiendo a Archivos zip
        uses: actions/upload-artifact@v3
        with:
          name: mis-archivos
          path: archivos.zip
          
      - name:  Download Artefacto
        uses: actions/download-artifact@v3
        with:
          name: mis-archivos
          path: ~/artefacto

      - name: verificacio la descarga del arefactos
        run: ls -la ~/artefacto
