# This is a basic workflow to help you get started with Actions

name: ejercicio-2 CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ejercicio-2]

jobs:
  crear-acceder-contenedor:
    runs-on: self-hosted

    services:
      portal:
        image: httpd:latest
        ports:
          - 8080:80
    steps:
      - name: Acceder al portal
        run: curl http://localhost:8080
